import os

DEBUG = os.environ.get("HKSOVA_CONFIG_DEBUG", False)

SECRET_KEY = os.environ.get("HKSOVA_CONFIG_SECRET_KEY", None)
SECRET_PEPPER = os.environ.get("HKSOVA_CONFIG_SECRET_PEPPER", None)

MYSQL_HOST = os.environ.get("HKSOVA_CONFIG_MYSQL_HOST", None)
MYSQL_USER = os.environ.get("HKSOVA_CONFIG_MYSQL_USER", None)
MYSQL_PASSWORD = os.environ.get("HKSOVA_CONFIG_MYSQL_PASSWORD", None)
MYSQL_DB = os.environ.get("HKSOVA_CONFIG_MYSQL_DB", None)
MYSQL_CURSORCLASS = 'DictCursor'

MDEDITOR_LANGUAGE = 'en'
MDEDITOR_THEME = 'dark'
MDEDITOR_PREVIEW_THEME = 'dark'
MDEDITOR_EDITOR_THEME = 'pastel-on-dark'
